replicaCount: 3

image:
  repository: danielzerihon/k8s-microservice-monitoring
  pullPolicy: Always
  tag: latest

service:
  name: monitor-flask-app
  type: ClusterIP
  port: 5000
  targetPort: 5000

livenessProbe:
  httpGet:
    path: /metrics
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10

ingress:
  enabled: false

