name: My First GitHub Actions

on: 
  push:
  workflow_dispatch:
    inputs:
      metric_name:
        description: 'this parameter will generated as the prometheus metric name'
        default: 'bombastic'
        required: true
        type: string
        
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Set environment variable for metric name
      env:
        METRIC_NAME: "${{ inputs.metric_name }}"
      run: echo "${{ METRIC_NAME }}"
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install pytest

    - name: Run tests
      run: |
        pwd
        ls -ltr
        python github_pipline_tests/test_commit.py
